from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
from pydantic import BaseModel, EmailStr
from app.core.database import get_db
from app.models.models import User, Organization, AuditLog
from app.services.user_service import generate_user_id, ensure_default_operator

router = APIRouter()


class UserRegisterIn(BaseModel):
    full_name: str
    email: str
    organization_name: str
    organization_code: Optional[str] = None  # e.g., 'CBZ', 'BZT'
    role: str = "analyst"


class UserOut(BaseModel):
    id: str
    user_id: str
    full_name: str
    username: str
    email: str
    role: str
    organization_name: Optional[str] = None

    class Config:
        from_attributes = True


class OrgOut(BaseModel):
    id: str
    name: str
    code: str
    org_index: int
    user_counter: int

    class Config:
        from_attributes = True


@router.get("/me")
async def get_current_operator(db: AsyncSession = Depends(get_db)):
    """Returns the current SOC operator details with their autogenerated User ID."""
    user = await ensure_default_operator(db)
    org_res = await db.execute(select(Organization).where(Organization.id == user.org_id))
    org = org_res.scalar_one_or_none()

    return {
        "id": user.id,
        "user_id": user.user_id,
        "full_name": user.full_name,
        "username": user.username,
        "email": user.email,
        "role": user.role,
        "organization_name": org.name if org else "Argus SecOps"
    }


@router.post("/register")
async def register_user(
    req: UserRegisterIn,
    db: AsyncSession = Depends(get_db)
):
    """
    Registers a new user and automatically assigns a formatted User ID:
    AG-[ORG][ORG_NUM]-[USER_NUM] (e.g. AG-CBZ01-0001 or AG-BZT02-0001).
    """
    # Check if email is already taken
    existing = await db.execute(select(User).where(User.email == req.email))
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="User with this email already exists.")

    # Autogenerate User ID
    org, autogen_user_id = await generate_user_id(
        db,
        org_name=req.organization_name,
        preferred_code=req.organization_code
    )

    base_username = req.email.split("@")[0].lower().replace(".", "_")
    user = User(
        user_id=autogen_user_id,
        full_name=req.full_name,
        username=f"{base_username}_{org.user_counter}",
        email=req.email,
        hashed_password="sha256_hashed_placeholder",
        role=req.role,
        org_id=org.id,
        is_active=True
    )
    db.add(user)

    # Audit logging
    audit = AuditLog(
        actor_username="system",
        action="REGISTER_USER",
        target_resource="User",
        target_id=autogen_user_id,
        details={"full_name": req.full_name, "org": org.name, "user_id": autogen_user_id}
    )
    db.add(audit)

    await db.commit()
    await db.refresh(user)

    return {
        "status": "success",
        "message": f"User registered successfully with ID: {autogen_user_id}",
        "user": {
            "id": user.id,
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "role": user.role,
            "organization_name": org.name,
            "organization_code": org.code,
            "organization_index": f"{org.org_index:02d}",
            "user_index_in_org": f"{org.user_counter:04d}"
        }
    }


@router.get("", response_model=List[UserOut])
async def list_users(db: AsyncSession = Depends(get_db)):
    """Lists all registered users with their autogenerated User IDs."""
    result = await db.execute(select(User).order_by(desc(User.created_at)))
    users = result.scalars().all()
    user_list = []
    for u in users:
        org_name = None
        if u.org_id:
            org_res = await db.execute(select(Organization).where(Organization.id == u.org_id))
            org = org_res.scalar_one_or_none()
            if org:
                org_name = org.name
        user_list.append(
            UserOut(
                id=u.id,
                user_id=u.user_id,
                full_name=u.full_name,
                username=u.username,
                email=u.email,
                role=u.role,
                organization_name=org_name
            )
        )
    return user_list


@router.get("/organizations", response_model=List[OrgOut])
async def list_organizations(db: AsyncSession = Depends(get_db)):
    """Lists all registered organizations and user counters."""
    result = await db.execute(select(Organization).order_by(Organization.org_index))
    return result.scalars().all()
