import os
import uuid
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)
from app.core.config import settings
from app.services.signer import signer
from app.models import Alert, Device, IncidentReport


class PDFReportGenerator:
    def generate_incident_report(
        self,
        title: str,
        report_type: str,  # "EXECUTIVE" or "ANALYST"
        alerts: List[Alert],
        devices: List[Device],
        generated_by: str = "SecOps Lead Analyst"
    ) -> IncidentReport:
        """
        Generates a professional, cryptographic signed PDF incident report.
        Embeds SHA-256 checksum and Ed25519 digital signature for chain-of-custody.
        """
        report_id = str(uuid.uuid4())
        filename = f"argus_report_{report_type.lower()}_{report_id[:8]}.pdf"
        output_path = os.path.join(settings.REPORTS_DIR, filename)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )

        styles = getSampleStyleSheet()
        
        # Custom styles
        header_style = ParagraphStyle(
            'HeaderStyle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#0F172A')
        )
        sub_style = ParagraphStyle(
            'SubStyle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=15,
            textColor=colors.HexColor('#64748B')
        )
        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1E293B'),
            spaceBefore=14,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor('#334155')
        )
        badge_style = ParagraphStyle(
            'BadgeStyle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10,
            textColor=colors.whitesmoke
        )

        story = []

        # Header Title with Official Logo
        logo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "static", "img", "logo.png"))
        if os.path.exists(logo_path):
            from reportlab.platypus import Image as RLImage
            logo_img = RLImage(logo_path, width=44, height=44)
            header_table = Table([[
                logo_img,
                [
                    Paragraph(f"ARGUS // CYBERSECOPS INCIDENT REPORT", header_style),
                    Paragraph(f"Document Classification: RESTRICTED // Report Type: {report_type.upper()}", sub_style)
                ]
            ]], colWidths=[52, 478])
            header_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ]))
            story.append(header_table)
        else:
            story.append(Paragraph(f"ARGUS // CYBERSECOPS INCIDENT REPORT", header_style))
            story.append(Paragraph(f"Document Classification: RESTRICTED // Report Type: {report_type.upper()}", sub_style))

        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#2563EB'), spaceAfter=15))

        # Metadata Block
        gen_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        meta_data = [
            [
                Paragraph("<b>Report ID:</b>", body_style), Paragraph(report_id, body_style),
                Paragraph("<b>Generated By:</b>", body_style), Paragraph(generated_by, body_style)
            ],
            [
                Paragraph("<b>Timestamp:</b>", body_style), Paragraph(gen_time, body_style),
                Paragraph("<b>Scope:</b>", body_style), Paragraph(f"{len(alerts)} Incidents across {len(devices)} Endpoints", body_style)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[80, 180, 90, 180])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 15))

        # Executive Summary Section
        story.append(Paragraph("1. Executive Summary & Impact Assessment", h2_style))
        critical_count = sum(1 for a in alerts if a.severity == "CRITICAL")
        high_count = sum(1 for a in alerts if a.severity == "HIGH")
        med_count = sum(1 for a in alerts if a.severity == "MEDIUM")
        
        exec_summary_text = (
            f"This incident response document details security anomalies detected across enterprise endpoint devices. "
            f"A total of <b>{len(alerts)} security alerts</b> were evaluated and correlated with MITRE ATT&CK techniques. "
            f"Severity breakdown includes <b>{critical_count} Critical</b>, <b>{high_count} High</b>, and <b>{med_count} Medium</b> severity occurrences. "
            f"Immediate containment and remediation recommendations have been formulated to mitigate active insider threats and unauthorized access."
        )
        story.append(Paragraph(exec_summary_text, body_style))
        story.append(Spacer(1, 12))

        # Affected Devices Table
        story.append(Paragraph("2. Monitored Endpoints & Asset Impact", h2_style))
        device_table_data = [["Hostname", "OS", "Branch", "Risk Score", "Status"]]
        for d in devices:
            device_table_data.append([
                d.hostname,
                d.os_type.capitalize(),
                d.branch_name,
                f"{d.risk_score} / 100",
                d.status
            ])
        if len(device_table_data) == 1:
            device_table_data.append(["No active devices", "-", "-", "-", "-"])

        d_table = Table(device_table_data, colWidths=[120, 80, 150, 90, 90])
        d_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E293B')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ]))
        story.append(d_table)
        story.append(Spacer(1, 15))

        # Detailed Incidents & MITRE ATT&CK Mapping
        story.append(Paragraph("3. Detected Incidents & MITRE ATT&CK Mapping", h2_style))
        alert_rows = [["Severity", "Technique ID", "Technique Name", "Tactic", "Affected User / Host"]]
        for a in alerts:
            alert_rows.append([
                a.severity,
                a.mitre_technique_id or "N/A",
                (a.mitre_technique_name or a.title)[:28],
                a.mitre_tactic or "N/A",
                f"{a.username or 'system'}"
            ])
        if len(alert_rows) == 1:
            alert_rows.append(["None", "N/A", "No active alerts detected", "N/A", "-"])

        a_table = Table(alert_rows, colWidths=[65, 85, 170, 100, 110])
        a_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8.5),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ]))
        story.append(a_table)
        story.append(Spacer(1, 15))

        # Security Remediation Plan
        story.append(Paragraph("4. Prescribed Security Remediation Measures", h2_style))
        remediation_items = [
            "1. <b>Host Isolation:</b> Immediately quarantine compromised endpoints exhibiting high-severity LOLBin execution.",
            "2. <b>Credential Revocation:</b> Rotate passwords and invalidate active API tokens identified in unauthorized clipboard transfers.",
            "3. <b>Physical Verification:</b> Cross-reference camera anomaly captures with security access badge logs for unverified physical workstation occupants.",
            "4. <b>Print Auditing:</b> Enforce supervisor sign-off on spooled documents flagged under sensitive classification rules."
        ]
        for rem in remediation_items:
            story.append(Paragraph(rem, body_style))
            story.append(Spacer(1, 4))
        story.append(Spacer(1, 15))

        # Chain-of-Custody & Cryptographic Verification Footer
        story.append(Paragraph("5. Chain-of-Custody & Cryptographic Verification", h2_style))
        
        # Build first pass to generate bytes, calculate SHA-256, and sign
        doc.build(story)

        with open(output_path, "rb") as f:
            pdf_bytes = f.read()

        sha256_hash = signer.calculate_sha256(pdf_bytes)
        signature_hex = signer.sign(pdf_bytes)

        # Append Signature & Verification Page
        cert_story = story.copy()
        cert_story.append(Spacer(1, 10))
        
        sig_data = [
            [Paragraph("<b>Cryptographic Standard:</b>", body_style), Paragraph("SHA-256 Digest // Ed25519 Digital Signature", body_style)],
            [Paragraph("<b>SHA-256 Checksum:</b>", body_style), Paragraph(f"<code>{sha256_hash}</code>", body_style)],
            [Paragraph("<b>Ed25519 Signature:</b>", body_style), Paragraph(f"<code>{signature_hex[:64]}...</code>", body_style)],
            [Paragraph("<b>Verification URL:</b>", body_style), Paragraph("Verify this document at <code>/verify-report</code> using the public key", body_style)]
        ]
        sig_table = Table(sig_data, colWidths=[140, 390])
        sig_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#EFF6FF')),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#3B82F6')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#BFDBFE')),
        ]))
        cert_story.append(sig_table)

        # Re-build final certified PDF
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )
        doc.build(cert_story)

        # Final signature of the complete document
        with open(output_path, "rb") as f:
            final_bytes = f.read()
        final_sha256 = signer.calculate_sha256(final_bytes)
        final_signature = signer.sign(final_bytes)

        report_model = IncidentReport(
            id=report_id,
            title=title,
            report_type=report_type,
            generated_by=generated_by,
            sha256_hash=final_sha256,
            signature_hex=final_signature,
            file_path=output_path,
            mitre_summary={
                "total_alerts": len(alerts),
                "critical": critical_count,
                "high": high_count,
                "medium": med_count
            },
            alert_ids=[a.id for a in alerts]
        )

        return report_model


pdf_generator = PDFReportGenerator()
