import os
import uuid
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)
from app.core.config import settings
from app.services.signer import signer
from app.models import Alert, Device, IncidentReport


class PDFReportGenerator:
    def _create_flowables(
        self,
        report_id: str,
        report_type: str,
        alerts: List[Alert],
        devices: List[Device],
        generated_by: str,
        sig_data: Optional[Dict[str, str]] = None
    ) -> List[Any]:
        styles = getSampleStyleSheet()
        
        # Custom styles (Smooth Executive Black & White / Monochrome)
        header_style = ParagraphStyle(
            'HeaderStyle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#000000')
        )
        sub_style = ParagraphStyle(
            'SubStyle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor('#555555')
        )
        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=11.5,
            leading=15,
            textColor=colors.HexColor('#111111'),
            spaceBefore=11,
            spaceAfter=5
        )
        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            leading=12.5,
            textColor=colors.HexColor('#222222')
        )
        code_style = ParagraphStyle(
            'CodeStyle',
            parent=styles['Normal'],
            fontName='Courier',
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor('#111111')
        )

        story = []

        # Header Title with Official Logo
        logo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "static", "img", "logo.jpg"))
        if not os.path.exists(logo_path):
            logo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "static", "img", "logo.png"))

        if os.path.exists(logo_path):
            from reportlab.platypus import Image as RLImage
            logo_img = RLImage(logo_path, width=42, height=42)
            header_table = Table([[
                logo_img,
                [
                    Paragraph("ARTIS // INCIDENT SECURITY REPORT", header_style),
                    Paragraph(f"Document Classification: RESTRICTED // Report Type: {report_type.upper()}", sub_style)
                ]
            ]], colWidths=[48, 484])
            header_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ]))
            story.append(header_table)
        else:
            story.append(Paragraph("ARTIS // INCIDENT SECURITY REPORT", header_style))
            story.append(Paragraph(f"Document Classification: RESTRICTED // Report Type: {report_type.upper()}", sub_style))

        story.append(Spacer(1, 8))
        # Sleek, smooth black divider line (no bright colors)
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#111111'), spaceAfter=12))

        # Metadata Block (Smooth Monochrome Table)
        gen_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        meta_data = [
            [
                Paragraph("<b>Report ID:</b>", body_style), Paragraph(report_id, code_style),
                Paragraph("<b>Generated By:</b>", body_style), Paragraph(generated_by, body_style)
            ],
            [
                Paragraph("<b>Timestamp:</b>", body_style), Paragraph(gen_time, body_style),
                Paragraph("<b>Scope:</b>", body_style), Paragraph(f"{len(alerts)} Incidents across {len(devices)} Endpoints", body_style)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[80, 180, 90, 182])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8F8F8')),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor('#CCCCCC')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E5E5')),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 10))

        # Executive Summary Section
        story.append(Paragraph("1. Executive Summary & Impact Assessment", h2_style))
        critical_count = sum(1 for a in alerts if a.severity == "CRITICAL")
        high_count = sum(1 for a in alerts if a.severity == "HIGH")
        med_count = sum(1 for a in alerts if a.severity == "MEDIUM")
        
        exec_summary_text = (
            f"This incident response document details security anomalies detected across enterprise endpoint devices. "
            f"A total of <b>{len(alerts)} security alerts</b> were evaluated and correlated with MITRE ATT&CK techniques. "
            f"Severity breakdown includes <b>{critical_count} Critical</b>, <b>{high_count} High</b>, and <b>{med_count} Medium</b> severity occurrences. "
            f"Immediate containment and remediation recommendations have been formulated to mitigate active insider threats and unauthorized access."
        )
        story.append(Paragraph(exec_summary_text, body_style))
        story.append(Spacer(1, 8))

        # Affected Devices Table (Smooth Monochrome)
        story.append(Paragraph("2. Monitored Endpoints & Asset Impact", h2_style))
        device_table_data = [["Hostname", "OS", "Branch", "Risk Score", "Status"]]
        for d in devices:
            device_table_data.append([
                d.hostname,
                d.os_type.capitalize(),
                d.branch_name,
                f"{d.risk_score} / 100",
                d.status
            ])
        if len(device_table_data) == 1:
            device_table_data.append(["No active devices recorded", "-", "-", "-", "-"])

        d_table = Table(device_table_data, colWidths=[120, 80, 150, 92, 90])
        d_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#111111')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8.5),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('PADDING', (0, 0), (-1, -1), 4.5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E0E0E0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8F8F8')]),
        ]))
        story.append(d_table)
        story.append(Spacer(1, 10))

        # Detailed Incidents & MITRE ATT&CK Mapping (Smooth Monochrome)
        story.append(Paragraph("3. Detected Incidents & MITRE ATT&CK Mapping", h2_style))
        alert_rows = [["Severity", "Technique ID", "Technique Name", "Tactic", "Affected User / Host"]]
        for a in alerts:
            alert_rows.append([
                a.severity,
                a.mitre_technique_id or "N/A",
                (a.mitre_technique_name or a.title)[:28],
                a.mitre_tactic or "N/A",
                f"{a.username or 'system'}"
            ])
        if len(alert_rows) == 1:
            alert_rows.append(["None", "N/A", "No active alerts detected", "N/A", "-"])

        a_table = Table(alert_rows, colWidths=[60, 85, 175, 100, 112])
        a_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#111111')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('PADDING', (0, 0), (-1, -1), 4.5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E0E0E0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8F8F8')]),
        ]))
        story.append(a_table)
        story.append(Spacer(1, 10))

        # Security Remediation Plan
        story.append(Paragraph("4. Prescribed Security Remediation Measures", h2_style))
        remediation_items = [
            "1. <b>Host Isolation:</b> Immediately quarantine compromised endpoints exhibiting high-severity LOLBin execution.",
            "2. <b>Credential Revocation:</b> Rotate passwords and invalidate active API tokens identified in unauthorized clipboard transfers.",
            "3. <b>Physical Verification:</b> Cross-reference camera anomaly captures with security access badge logs for unverified physical occupants.",
            "4. <b>Print Auditing:</b> Enforce supervisor sign-off on spooled documents flagged under sensitive classification rules."
        ]
        for rem in remediation_items:
            story.append(Paragraph(rem, body_style))
            story.append(Spacer(1, 3))
        story.append(Spacer(1, 10))

        # Chain-of-Custody & Cryptographic Verification Footer
        story.append(Paragraph("5. Chain-of-Custody & Cryptographic Verification", h2_style))
        story.append(Spacer(1, 4))
        
        # Smooth Monochrome Cryptographic Card (No bright blues or colors)
        sha256_val = sig_data.get("sha256", "Pending signature calculation...") if sig_data else "Calculating cryptographic hash..."
        sig_val = sig_data.get("signature", "Pending signature calculation...") if sig_data else "Calculating digital signature..."
        
        sig_table_rows = [
            [Paragraph("<b>Cryptographic Standard:</b>", body_style), Paragraph("SHA-256 Digest // Ed25519 Digital Signature", body_style)],
            [Paragraph("<b>SHA-256 Checksum:</b>", body_style), Paragraph(f"<code>{sha256_val}</code>", code_style)],
            [Paragraph("<b>Ed25519 Signature:</b>", body_style), Paragraph(f"<code>{sig_val[:64]}...</code>" if len(sig_val) > 64 else f"<code>{sig_val}</code>", code_style)],
            [Paragraph("<b>Verification URL:</b>", body_style), Paragraph("Verify this document at <code>/verify-report</code> using the public key", body_style)]
        ]
        sig_table = Table(sig_table_rows, colWidths=[140, 392])
        sig_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F9F9F9')),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor('#333333')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E5E5')),
        ]))
        story.append(sig_table)

        return story

    def generate_incident_report(
        self,
        title: str,
        report_type: str,  # "EXECUTIVE" or "ANALYST"
        alerts: List[Alert],
        devices: List[Device],
        generated_by: str = "SecOps Lead Analyst"
    ) -> IncidentReport:
        """
        Generates a professional, cryptographic signed PDF incident report.
        Embeds SHA-256 checksum and Ed25519 digital signature for chain-of-custody.
        """
        report_id = str(uuid.uuid4())
        filename = f"argus_report_{report_type.lower()}_{report_id[:8]}.pdf"
        output_path = os.path.join(settings.REPORTS_DIR, filename)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )

        # Pass 1: Build draft to obtain content bytes for initial hash & sign
        pass1_story = self._create_flowables(
            report_id=report_id,
            report_type=report_type,
            alerts=alerts,
            devices=devices,
            generated_by=generated_by,
            sig_data=None
        )
        doc.build(pass1_story)

        with open(output_path, "rb") as f:
            pdf_bytes = f.read()

        sha256_hash = signer.calculate_sha256(pdf_bytes)
        signature_hex = signer.sign(pdf_bytes)

        # Pass 2: Re-build complete certified PDF with fresh flowables and embedded cryptographic digest
        final_doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )
        pass2_story = self._create_flowables(
            report_id=report_id,
            report_type=report_type,
            alerts=alerts,
            devices=devices,
            generated_by=generated_by,
            sig_data={"sha256": sha256_hash, "signature": signature_hex}
        )
        final_doc.build(pass2_story)

        # Final signature of the complete document
        with open(output_path, "rb") as f:
            final_bytes = f.read()
        final_sha256 = signer.calculate_sha256(final_bytes)
        final_signature = signer.sign(final_bytes)

        critical_count = sum(1 for a in alerts if a.severity == "CRITICAL")
        high_count = sum(1 for a in alerts if a.severity == "HIGH")
        med_count = sum(1 for a in alerts if a.severity == "MEDIUM")

        report_model = IncidentReport(
            id=report_id,
            title=title,
            report_type=report_type,
            generated_by=generated_by,
            sha256_hash=final_sha256,
            signature_hex=final_signature,
            file_path=output_path,
            mitre_summary={
                "total_alerts": len(alerts),
                "critical": critical_count,
                "high": high_count,
                "medium": med_count
            },
            alert_ids=[a.id for a in alerts]
        )

        return report_model


pdf_generator = PDFReportGenerator()

