import re
from typing import Tuple, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from app.models.models import Organization, User


def extract_org_code(org_name: str, preferred_code: Optional[str] = None) -> str:
    """
    Extracts an organization abbreviation:
    - If preferred_code is given (e.g. 'CBZ'), uses it.
    - If parentheses exist like 'Commercial Bank of Zimbabwe (CBZ)', extracts 'CBZ'.
    - If 'Bizmark Technology', extracts 'BZT'.
    - If multiple words, takes initials.
    - If single word like 'Argus', takes first 3 letters 'ARG'.
    """
    if preferred_code:
        clean = re.sub(r'[^A-Za-z0-9]', '', preferred_code).upper()
        if clean:
            return clean[:4]

    # Check for abbreviation in parentheses e.g. "Commercial Bank of Zimbabwe (CBZ)"
    match = re.search(r'\(([A-Za-z0-9]{2,5})\)', org_name)
    if match:
        return match.group(1).upper()

    words = [w for w in re.split(r'[\s\-_]+', org_name) if w]
    if len(words) >= 3:
        code = "".join(w[0] for w in words[:3]).upper()
    elif len(words) == 2:
        w1, w2 = words[0], words[1]
        if w1.lower() == "bizmark" and w2.lower().startswith("tech"):
            code = "BZT"
        elif len(w1) >= 2 and len(w2) >= 1:
            code = (w1[:2] + w2[0]).upper()
        else:
            code = (w1[0] + w2[:2]).upper()
    elif len(words) == 1:
        code = words[0][:3].upper()
    else:
        code = "ORG"

    return code[:4]


async def generate_user_id(
    db: AsyncSession,
    org_name: str,
    preferred_code: Optional[str] = None
) -> Tuple[Organization, str]:
    """
    Autogenerates User ID in the exact format:
    AG-[ORG][ORG_INDEX]-[USER_COUNT]
    Examples:
      - CBZ (1st registered org, 1st user): AG-CBZ01-0001
      - CBZ (1st registered org, 2nd user): AG-CBZ01-0002
      - Bizmark Technology (2nd registered org, 1st user): AG-BZT02-0001
    """
    clean_org_name = org_name.strip()

    # Check if organization already exists in database
    stmt = select(Organization).where(func.lower(Organization.name) == clean_org_name.lower())
    res = await db.execute(stmt)
    org = res.scalar_one_or_none()

    if not org:
        # Increment total registered organizations count
        count_stmt = select(func.count(Organization.id))
        total_orgs = (await db.scalar(count_stmt)) or 0
        org_index = total_orgs + 1
        code = extract_org_code(clean_org_name, preferred_code)

        org = Organization(
            name=clean_org_name,
            code=code,
            org_index=org_index,
            user_counter=1
        )
        db.add(org)
        await db.flush()
        user_seq = 1
    else:
        org.user_counter += 1
        user_seq = org.user_counter
        await db.flush()

    user_id = f"AG-{org.code}{org.org_index:02d}-{user_seq:04d}"
    return org, user_id


async def ensure_default_operator(db: AsyncSession) -> User:
    """
    Ensures the default SOC Lead Analyst 'Alex Mercer' is provisioned
    with autogenerated User ID 'AG-ARG01-0001'.
    """
    stmt = select(User).where(User.username == "alex_mercer")
    res = await db.execute(stmt)
    user = res.scalar_one_or_none()

    if not user:
        org, user_id = await generate_user_id(db, "Argus SecOps", preferred_code="ARG")
        user = User(
            user_id=user_id,
            full_name="Alex Mercer",
            username="alex_mercer",
            email="alex.mercer@argus.secops",
            hashed_password="sha256_hashed_placeholder_for_demo",
            role="admin",
            org_id=org.id,
            is_active=True
        )
        db.add(user)
        await db.commit()
        await db.refresh(user)

    return user
